// Icons that should have the white filter applied (dark icons that need inversion)
export const WHITE_FILTER_ICONS = new Set([
  "openai.svg",
  "anthropic.svg",
  "github.svg",
  "apple.svg",
  "vercel.svg",
  "ollama.svg",
  "xai.svg",
  "zeroone.svg",
  "ibm.svg",
  "liquid.svg",
  "inception.svg",
  "nousresearch.svg",
  "inflection.svg",
  "ai21.svg",
  "dolphin.svg",
  "zai.svg",
  "groq.svg",
  "openrouter.svg",
  "lmstudio.svg",
  "lambda.svg",
  "replicate.svg",
  "nebius.svg",
  "friendli.svg",
  "parasail.svg",
  "baseten.svg",
  "cursor.svg",
  "githubcopilot.svg",
  "cline.svg",
  "goose.svg",
  "manus.svg",
  "pear.svg",
  "edendark.svg",
  "moonshot.svg",
  "continue.svg",
  "windsurf.svg",
  "agentzero.svg",
  "capacity.svg",
  "parallel.svg",
]);

// Icon file mappings for lab IDs
export const LAB_ICON_FILES: Record<string, string> = {
  openai: "openai.svg",
  anthropic: "anthropic.svg",
  google: "gemini-color.svg",
  meta: "meta-color.svg",
  deepseek: "deepseek-color.svg",
  xai: "xai.svg",
  mistral: "mistral-color.svg",
  alibaba: "alibaba-color.svg",
  cohere: "cohere-color.svg",
  ai21: "ai21.svg",
  amazon: "aws-color.svg",
  microsoft: "microsoft-color.svg",
  nvidia: "nvidia-color.svg",
  perplexity: "perplexity-color.svg",
  baidu: "baidu-color.svg",
  tencent: "hunyuan-color.svg",
  bytedance: "bytedance-color.svg",
  zhipu: "zai.svg",
  minimax: "minimax-color.svg",
  "01ai": "zeroone.svg",
  moonshot: "moonshot.svg",
  huggingface: "huggingface-color.svg",
  inflection: "inflection.svg",
  together: "together-color.svg",
  stepfun: "stepfun-color.svg",
  upstage: "upstage-color.svg",
  databricks: "dbrx-color.svg",
  snowflake: "snowflake-color.svg",
  liquid: "liquid.svg",
  tii: "tii-color.svg",
  baichuan: "baichuan-color.svg",
  reka: "reka_small.svg",
  lg: "lg-color.svg",
  "korea-telecom": "korea-telecom_small.webp",
  ibm: "ibm.svg",
  apple: "apple.svg",
  xiaomi: "xiaomi_small.svg",
  inception: "inception.svg",
  inclusionai: "inclusionai_small.webp",
  "prime-intellect": "prime-intellect_small.svg",
  openchat: "openchat-color.svg",
  arcee: "arcee-color.svg",
  nous: "nousresearch.svg",
  dolphin: "dolphin.svg",
  mbzuai: "mbzuai_small.svg",
  ai2: "ai2-color.svg",
  motif: "motif_small.svg",
  wenxiaobai: "wenxiaobai.svg",
  servicenow: "servicenow_small.svg",
  kwaikat: "kwaikat_small.svg",
  naver: "naver_small.svg",
  "deep-cogito": "deepcogito-color.svg",
  kwaipilot: "kwaikat_small.svg",
};

// Icon file mappings for provider IDs
export const PROVIDER_ICON_FILES: Record<string, string> = {
  openrouter: "openrouter.svg",
  together: "together-color.svg",
  fireworks: "fireworks-color.svg",
  groq: "groq.svg",
  replicate: "replicate.svg",
  deepinfra: "deepinfra-color.svg",
  cerebras: "cerebras-color.svg",
  "vertex-ai": "vertexai-color.svg",
  "alibaba-cloud": "alibabacloud-color.svg",
  databricks: "dbrx-color.svg",
  clarifai: "civitai-color.svg",
  lightning: "leptonai-color.svg",
  baseten: "baseten.svg",
  "snowflake-cortex": "snowflake-color.svg",
  hyperbolic: "hyperbolic-color.svg",
  parasail: "parasail.svg",
  friendli: "friendli.svg",
  nebius: "nebius.svg",
  siliconflow: "siliconcloud-color.svg",
  novita: "novita-color.svg",
  lambda: "lambda.svg",
  scaleway: "cloudflare-color.svg",
  "aws-bedrock": "bedrock-color.svg",
  "azure-ai": "azureai-color.svg",
  "nvidia-nim": "nvidia-color.svg",
  lepton: "leptonai-color.svg",
  "huggingface-inference": "huggingface-color.svg",
  sambanova: "sambanova-color.svg",
  ollama: "ollama.svg",
  lmstudio: "lmstudio.svg",
  parallel: "parallel.svg",
  you: "you.svg",
  perplexity: "perplexity-color.svg",
  streamlake: "kwaikat_small.svg",
};

// Icon file mappings for app IDs
export const APP_ICON_FILES: Record<string, string> = {
  // IDEs
  cursor: "cursor.svg",
  windsurf: "windsurf.svg",
  zed: "zed.svg",
  antigravity: "antigravity.svg",
  kiro: "aws-color.svg",
  pear: "pear.svg",
  trae: "trae-color.svg",
  roocode: "roocode.svg",
  orchids: "orchids.svg",
  // CLI tools
  "claude-code": "anthropic.svg",
  jules: "jules.svg",
  "gemini-cli": "gemini-color.svg",
  "mistral-vibe": "mistral-color.svg",
  "qwen-code": "qwen-color.svg",
  aider: "aider.svg",
  opencode: "opencode.svg",
  warp: "warp.svg",
  amp: "amp.svg",
  "openai-codex-cli": "openai.svg",
  "copilot-cli": "githubcopilot.svg",
  "augment-cli": "augment.svg",
  cline: "cline.svg",
  "kimi-cli": "kimi-color.svg",
  mycoder: "github.svg",
  "goose-cli": "goose.svg",
  "openhands-cli": "openhands.svg",
  // Browsers
  "chatgpt-atlas": "openai.svg",
  dia: "dia.svg",
  "edge-copilot": "bing-color.svg",
  "opera-neon": "opera.svg",
  sigma: "sigma.svg",
  "browser-use": "browseruse.svg",
  fellou: "fellou.svg",
  "ecosia-ai": "ecosia.svg",
  // Plugins
  "cline-plugin": "cline.svg",
  kilo: "kilo.svg",
  "augment-plugin": "augment.svg",
  "tabnine-nvim": "tabnine.svg",
  "amazon-q": "bedrock-color.svg",
  "continue-plugin": "continue.svg",
  // Physical devices
  "rabbit-r1": "rabbit.svg",
  pickle: "pickle.svg",
  // Agents
  devin: "devin.svg",
  v0: "vercel.svg",
  lovable: "lovable.svg",
  bolt: "bolt.svg",
  "replit-agent": "replit-color.svg",
  manus: "manus.svg",
  factory: "factory.svg",
  "agent-zero": "agentzero.svg",
  eden: "edendark.svg",
  zo: "zo.svg",
  phoenix: "phoenix.svg",
  daytona: "daytona.svg",
  greptile: "greptile-color.svg",
  morph: "morph-color.svg",
  capacity: "capacity.svg",
  command: "command.svg",
  "create-xyz": "createxyz.svg",
  softgen: "softgen.svg",
  dyad: "dyad.svg",
  tempo: "tempo.svg",
  rocket: "rocket.svg",
  superdesign: "superdesign.svg",
  semgrep: "semgrep.svg",
  uipath: "uipath.svg",
  atoms: "atoms.svg",
  n8n: "n8n-color.svg",
  character: "character.svg",
};
